name: "yolov8"
platform: "tensorrt_plan"
max_batch_size: 4

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 84, 8400 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 2, 4 ]
  max_queue_delay_microseconds: 5000
  preserve_ordering: true
}

instance_group [
  { kind: KIND_GPU count: 1 }
]

model_transaction_policy { decoupled: false }
