const lanesEl = document.querySelector('#lanes');
const clockEl = document.querySelector('#clock');
const playBtn = document.querySelector('#play');
const speedEl = document.querySelector('#speed');
const speedValue = document.querySelector('#speedValue');
const eventEl = document.querySelector('#event');
const detailToggle = document.querySelector('#detailToggle');
const languageToggle = document.querySelector('#languageToggle');
const modeNames = { none: {en:'No double buffer, no multiple streams', zh:'无双缓冲、无多 Stream'}, cpu: {en:'CPU double buffering only', zh:'只有 CPU 双缓冲'}, both: {en:'CPU double buffering + 2 CUDA streams', zh:'CPU双缓冲+2个 CUDA stream'} };
let language = 'en';
let mode = 'both', time = 0, playing = false, detailed = false, last = performance.now(), selected = null;
const ui = {
  title:['CPU double buffering and TensorRT CUDA streams','CPU 双缓冲与 TensorRT 多 CUDA Stream'], lede:['Move through the timeline: the CPU prepares the next frame while the GPU transfers or computes the previous one. These are complementary layers of overlap.','拖动时间线观察：CPU 在准备下一帧的同时，GPU 正在搬运或计算上一帧。两层重叠互补，而不是同一件事。'], modeNone:modeNames.none, modeCpu:modeNames.cpu, modeBoth:modeNames.both, speed:['Speed','速度'], time:['Time','时间'], prep:['CPU preprocessing','CPU 预处理'], compute:['TensorRT compute','TensorRT 计算'], post:['CPU postprocessing','CPU 后处理'], card1h:['What does CPU double buffering solve?','CPU 双缓冲解决什么？'], card1p:['Two independent slots let the <b>CPU thread</b> alternate between buffers A and B: while the GPU uses A, the CPU prepares B. This hides host-side preparation time.','两个独立 slot 让 <b>CPU 线程</b>交替写入 buffer A/B：GPU 使用 A 时，CPU 可准备 B。它隐藏的是主机端准备时间。'], card2h:['What do multiple CUDA streams solve?','多 CUDA Stream 解决什么？'], card2p:['Each slot has its own stream and execution context. With pinned memory and asynchronous APIs, <b>H2D copies</b> can overlap Tensor Core computation in another stream.','每个 slot 有自己的 stream 和 execution context。借助 pinned memory 与异步 API，<b>H2D 拷贝</b>可以和另一 stream 的 Tensor Core 计算并行。'], card3h:['Ownership boundaries when combined','组合时的所有权边界'], card3p:['CPU finishes a slot → an event releases H2D; H2D completes → inference reads; compute completes → the slot returns to CPU. Independent buffers, contexts, and streams are required for safe concurrency.','CPU 写完 slot → 事件通知 H2D；H2D 完成 → 推理读取；计算完成 → slot 归还 CPU。没有独立 buffer、context、stream 就不能安全并发。'], hint:['Tip: click any timeline block to inspect its stage. This is a conceptual model, not a benchmark for a specific GPU.','提示：点击任意时间线上的帧，查看它经历的阶段。动画是概念模型，不代表特定 GPU 的实际时长。']
};
const zhText = {'CPU / slot A':'CPU / 插槽 A', 'CPU / slot B':'CPU / 插槽 B', 'GPU / Stream 0':'GPU / 流 0', 'GPU / Stream 1':'GPU / 流 1', 'CPU / 后处理 worker':'CPU / 后处理工作线程', 'CPU / 单缓冲':'CPU / 单缓冲', 'GPU / 默认 Stream':'GPU / 默认流', 'GPU / 推理':'GPU / 推理', 'CPU / 准备（串行生产）':'CPU / 准备（串行生产）', 'slot A / Host input':'插槽 A / 主机输入', 'slot A / Device + context':'插槽 A / 设备资源与执行上下文', 'slot A / Output':'插槽 A / 输出', 'slot B / Host input':'插槽 B / 主机输入', 'slot B / Device + context':'插槽 B / 设备资源与执行上下文', 'slot B / Output':'插槽 B / 输出'};
function tr(value) { if (language === 'zh') return zhText[value] || value; return value.replace('预处理','Preprocess').replace('后处理','Postprocess').replace('计算','Compute').replace('输入','Input').replace('完成','complete').replace('可复用','reusable').replace('默认 Stream','default stream').replace('推理','Inference').replace('串行生产','serial producer').replace('后处理 worker','Postprocessing worker').replace('资源生命周期','Resource lifecycle').replace('色块结束即该资源可复用','A resource is reusable when its block ends').replace('当前时刻','Current time').replace('正在','is running'); }
function applyLanguage() { document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'; document.documentElement.dataset.language = language; document.title = language === 'zh' ? '异步视频流水线：双缓冲 × CUDA Stream' : 'Async video pipeline: double buffering × CUDA streams'; document.querySelectorAll('[data-i18n]').forEach(el => { const value=ui[el.dataset.i18n]; if (value) el.innerHTML=Array.isArray(value) ? value[language === 'zh' ? 1 : 0] : value[language]; }); document.querySelector('#play').textContent=playing ? (language === 'zh' ? '❚❚ 暂停' : '❚❚ Pause') : (language === 'zh' ? '▶ 播放' : '▶ Play'); document.querySelector('#reset').textContent=language === 'zh' ? '↺ 重置' : '↺ Reset'; detailToggle.textContent=detailed ? (language === 'zh' ? '▾ 隐藏资源生命周期' : '▾ Hide resource lifecycle') : (language === 'zh' ? '▸ 资源生命周期' : '▸ Resource lifecycle'); languageToggle.textContent=language === 'zh' ? 'EN' : '中文'; languageToggle.setAttribute('aria-label', language === 'zh' ? 'Switch to English' : '切换至简体中文'); render(); }

const total = 11;
const base = {
  none: [{name:'CPU / 单缓冲',jobs:[['F0 预处理',0,1,'prep'],['F0 后处理',2.9,3.4,'post'],['F1 预处理',3.4,4.4,'prep'],['F1 后处理',6.3,6.8,'post'],['F2 预处理',6.8,7.8,'prep'],['F2 后处理',9.7,10.2,'post']]},{name:'GPU / 默认 Stream',jobs:[['F0 H2D',1,1.4,'h2d'],['F0 计算',1.4,2.6,'compute'],['F0 D2H',2.6,2.9,'result'],['F1 H2D',4.4,4.8,'h2d'],['F1 计算',4.8,6,'compute'],['F1 D2H',6,6.3,'result'],['F2 H2D',7.8,8.2,'h2d'],['F2 计算',8.2,9.4,'compute'],['F2 D2H',9.4,9.7,'result']]}],
  cpu: [{name:'CPU / slot A',jobs:[['F0 预处理',0,1.5,'prep'],['F2 预处理',3.6,5.1,'prep']]},{name:'CPU / slot B',jobs:[['F1 预处理',1.5,3,'prep'],['F3 预处理',5.5,7,'prep']]},{name:'GPU / 推理',jobs:[['F0 H2D',1.5,1.9,'h2d'],['F0 计算',1.9,3.2,'compute'],['F0 D2H',3.2,3.5,'result'],['F1 H2D',3.5,3.9,'h2d'],['F1 计算',3.9,5.2,'compute'],['F1 D2H',5.2,5.5,'result'],['F2 H2D',5.5,5.9,'h2d'],['F2 计算',5.9,7.2,'compute'],['F2 D2H',7.2,7.5,'result'],['F3 H2D',7.5,7.9,'h2d'],['F3 计算',7.9,9.2,'compute'],['F3 D2H',9.2,9.5,'result']]},{name:'CPU / 后处理 worker',jobs:[['F0 后处理',3.5,4,'post'],['F1 后处理',5.5,6,'post'],['F2 后处理',7.1,7.6,'post'],['F3 后处理',8.6,9.1,'post']]}],
  both: [{name:'CPU / slot A',jobs:[['F0 预处理',0,1.5,'prep'],['F2 预处理',3.8,5.3,'prep'],['F4 预处理',7.6,8.5,'prep']]},{name:'CPU / slot B',jobs:[['F1 预处理',1.5,3,'prep'],['F3 预处理',5.3,6.8,'prep']]},{name:'GPU / Stream 0',jobs:[['F0 H2D',1.5,2.2,'h2d'],['F0 计算',2.2,3.6,'compute'],['F0 D2H',3.6,3.8,'result'],['F2 H2D',5.3,6,'h2d'],['F2 计算',6,7.4,'compute'],['F2 D2H',7.4,7.6,'result'],['F4 H2D',8.5,9.2,'h2d'],['F4 计算',9.2,10.6,'compute'],['F4 D2H',10.6,10.8,'result']]},{name:'GPU / Stream 1',jobs:[['F1 H2D',3,3.7,'h2d'],['F1 计算',3.7,5.1,'compute'],['F1 D2H',5.1,5.3,'result'],['F3 H2D',6.8,7.5,'h2d'],['F3 计算',7.5,8.9,'compute'],['F3 D2H',8.9,9.1,'result']]},{name:'CPU / 后处理 worker',jobs:[['F0 后处理',3.8,4.2,'post'],['F1 后处理',5.3,5.7,'post'],['F2 后处理',7.6,8,'post'],['F3 后处理',9.1,9.5,'post'],['F4 后处理',10.8,11,'post']]}]
};
const resourceDetail = [
  {name:'slot A / Host input', jobs:[['F0 输入 → H2D 完成',0,2.2,'prep'],['F2 输入 → H2D 完成',3.8,6,'prep'],['F4 输入 → H2D 完成',7.6,9.2,'prep']]},
  {name:'slot A / Device + context', jobs:[['F0 stream 0',1.5,3.6,'compute'],['F2 stream 0',5.3,7.4,'compute'],['F4 stream 0',8.5,10.6,'compute']]},
  {name:'slot A / Output', jobs:[['F0 D2H 后可复用',3.6,3.8,'result'],['F2 D2H 后可复用',7.4,7.6,'result'],['F4 D2H 后可复用',10.6,10.8,'result']]},
  {name:'slot B / Host input', jobs:[['F1 输入 → H2D 完成',1.5,3.7,'prep'],['F3 输入 → H2D 完成',5.3,7.5,'prep']]},
  {name:'slot B / Device + context', jobs:[['F1 stream 1',3,5.1,'compute'],['F3 stream 1',6.8,8.9,'compute']]},
  {name:'slot B / Output', jobs:[['F1 D2H 后可复用',5.1,5.3,'result'],['F3 D2H 后可复用',8.9,9.1,'result']]}
];
function render(){ lanesEl.innerHTML=''; const active=[]; base[mode].forEach(lane=>{ const row=document.createElement('div'); row.className='lane'; row.innerHTML=`<div class="lane-label">${lane.name}</div><div class="track"></div>`; const track=row.lastElementChild; lane.jobs.forEach(j=>{const [label,start,end,kind]=j; const el=document.createElement('div'); el.className=`job ${kind}${time>=start&&time<end?' running':''}`; el.textContent=tr(label); el.style.left=`${start/total*100}%`; el.style.width=`${(end-start)/total*100}%`; el.dataset.info=`${label}：${start.toFixed(1)}–${end.toFixed(1)} s`; if(time>=start&&time<end) active.push(`${tr(lane.name)} ${language === 'zh' ? '正在' : 'is running'} ${tr(label)}`); el.onclick=()=>{document.querySelectorAll('.job').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');eventEl.textContent=el.dataset.info;}; track.appendChild(el);}); lanesEl.appendChild(row); }); if (detailed && mode === 'both') {
  const heading = document.createElement('div'); heading.className = 'detail-heading'; heading.textContent = language === 'zh' ? '细粒度资源生命周期（色块结束即该资源可复用）' : 'Fine-grained resource lifecycle (a resource is reusable when its block ends)'; lanesEl.appendChild(heading);
  resourceDetail.forEach(lane => { const row=document.createElement('div'); row.className='lane detail-lane'; row.innerHTML=`<div class="lane-label">${lane.name}</div><div class="track"></div>`; const track=row.lastElementChild; lane.jobs.forEach(j=>{const [label,start,end,kind]=j; const el=document.createElement('div'); el.className=`job ${kind}${time>=start&&time<end?' running':''}`; el.textContent=tr(label); el.style.left=`${start/total*100}%`; el.style.width=`${(end-start)/total*100}%`; track.appendChild(el);}); lanesEl.appendChild(row); });
}
const playhead=document.createElement('div'); playhead.className='playhead'; playhead.style.left=`calc(var(--label-width) + (100% - var(--label-width)) * ${time / total})`; lanesEl.appendChild(playhead); clockEl.textContent=`${time.toFixed(1)} s · ${modeNames[mode][language]}`; eventEl.textContent=active.length ? (language === 'zh' ? `此刻并行发生：${active.join('；')}` : `Running now: ${active.join('; ')}`) : (language === 'zh' ? '此刻没有任务执行：等待可用 slot 或下一帧。' : 'Nothing is running: waiting for an available slot or the next frame.'); }
function tick(now){ const dt=(now-last)/1000; last=now; if(playing){time+=dt*Number(speedEl.value); if(time>total){time=0;} render();} requestAnimationFrame(tick); }
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));time=0; if(mode!=='both'){detailed=false; detailToggle.classList.remove('active'); detailToggle.setAttribute('aria-pressed','false'); detailToggle.textContent='▸ 资源生命周期';} detailToggle.classList.toggle('visible',mode==='both'); render();});
languageToggle.onclick=()=>{ language=language === 'en' ? 'zh' : 'en'; applyLanguage(); };
detailToggle.onclick=()=>{ detailed=!detailed; detailToggle.classList.toggle('active',detailed); detailToggle.setAttribute('aria-pressed',detailed); detailToggle.textContent=detailed?'▾ 隐藏资源生命周期':'▸ 资源生命周期'; render(); };
playBtn.onclick=()=>{playing=!playing; applyLanguage();}; document.querySelector('#reset').onclick=()=>{time=0;playing=false;playBtn.textContent='▶ 播放';render();}; speedEl.oninput=()=>speedValue.textContent=`${speedEl.value}×`;
detailToggle.classList.add('visible');
applyLanguage(); requestAnimationFrame(tick);
