#include "frame_scheduler.hpp"
#include <algorithm>
#include <stdexcept>
namespace lesson21 {
FrameScheduler::FrameScheduler(std::vector<cv::Mat> sources,std::size_t count,std::size_t capacity,OverloadPolicy policy,std::chrono::milliseconds interval):sources_(std::move(sources)),frames_per_source_(count),interval_(interval){if(sources_.empty()||count==0)throw std::invalid_argument("sources and frame count must be non-empty");for(const auto&i:sources_)if(i.empty())throw std::invalid_argument("source image is empty");for(size_t i=0;i<sources_.size();++i)queues_.push_back(std::make_unique<BoundedQueue<ScheduledFrame>>(capacity,policy));}
FrameScheduler::~FrameScheduler(){stop(true);}
void FrameScheduler::start(){if(!workers_.empty())throw std::logic_error("scheduler already started");for(size_t stream=0;stream<sources_.size();++stream)workers_.emplace_back([this,stream]{for(size_t frame=0;frame<frames_per_source_&&!stopping_;++frame){ScheduledFrame item{sources_[stream],{stream,frame,0,Clock::now(),{}}};++captured_;if(!queues_[stream]->push(std::move(item)))break;if(interval_.count())std::this_thread::sleep_for(interval_);}queues_[stream]->close(false);++finished_;});}
std::vector<ScheduledFrame> FrameScheduler::next_batch(size_t maximum,std::chrono::milliseconds timeout){if(maximum==0)throw std::invalid_argument("batch maximum must be positive");std::vector<ScheduledFrame> batch;auto deadline=Clock::now()+timeout;while(batch.size()<maximum){bool found=false;for(size_t checked=0;checked<queues_.size();++checked){size_t index=(cursor_+checked)%queues_.size();auto item=queues_[index]->try_pop();if(item){item->metadata.batch_index=batch.size();batch.push_back(std::move(*item));cursor_=(index+1)%queues_.size();found=true;break;}}if(!found){if(done()||Clock::now()>=deadline)break;std::this_thread::sleep_for(std::chrono::microseconds(100));}}return batch;}
void FrameScheduler::stop(bool discard) noexcept{stopping_=true;for(auto&q:queues_)q->close(discard);for(auto&t:workers_)if(t.joinable())t.join();workers_.clear();}
size_t FrameScheduler::evicted()const{size_t n=0;for(auto&q:queues_)n+=q->evicted();return n;}size_t FrameScheduler::queue_peak()const{size_t n=0;for(auto&q:queues_)n=std::max(n,q->peak());return n;}bool FrameScheduler::done()const{return finished_==sources_.size()&&std::all_of(queues_.begin(),queues_.end(),[](const auto&q){return q->empty();});}
}
