#include "tensorrt_backend.hpp"
#include <NvInfer.h>
#include <cuda_runtime.h>
#include <nppi_geometry_transforms.h>
#include <fstream>
#include <numeric>
#include <stdexcept>
#include <memory>
#include <iostream>
#include <cstring>
namespace lesson21 { namespace {
void ck(cudaError_t e,const char* s){if(e!=cudaSuccess)throw std::runtime_error(std::string(s)+": "+cudaGetErrorString(e));}
class Log:public nvinfer1::ILogger{void log(Severity s,const char*m) noexcept override{if(s<=Severity::kWARNING)std::cerr<<"[TRT] "<<m<<'\n';}};
struct S{cudaStream_t stream{};cudaEvent_t done{},p0{},p1{},i0{},i1{},d0{},d1{};std::unique_ptr<nvinfer1::IExecutionContext> ctx;void* in{};void*out{};std::size_t inbytes{},outbytes{};BatchMetadata meta;std::vector<float> host;};
std::vector<char> read(const std::string&p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("cannot open engine "+p);auto n=f.tellg();std::vector<char>b((size_t)n);f.seekg(0);f.read(b.data(),n);return b;}
__global__ void norm(const unsigned char*src,float*dst,int w,int h,int step,int batch){int x=blockIdx.x*blockDim.x+threadIdx.x,y=blockIdx.y*blockDim.y+threadIdx.y;if(x>=w||y>=h)return;size_t q=(size_t)y*step+x*3, plane=(size_t)w*h;dst[batch*3*plane+y*w+x]=src[q+2]/255.f;dst[batch*3*plane+plane+y*w+x]=src[q+1]/255.f;dst[batch*3*plane+2*plane+y*w+x]=src[q]/255.f;}
}}
struct TensorRtBackend::Impl{Log log;std::unique_ptr<nvinfer1::IRuntime>rt;std::unique_ptr<nvinfer1::ICudaEngine>eng;std::string inname,outname;cv::Size size;std::vector<S> slots; std::vector<std::vector<void*>> staging;
Impl(const std::string&p,size_t n,cv::Size z):size(z){auto b=read(p);rt.reset(nvinfer1::createInferRuntime(log));if(!rt)throw std::runtime_error("runtime");eng.reset(rt->deserializeCudaEngine(b.data(),b.size()));if(!eng)throw std::runtime_error("engine");for(int i=0;i<eng->getNbIOTensors();++i){auto x=eng->getIOTensorName(i);if(eng->getTensorIOMode(x)==nvinfer1::TensorIOMode::kINPUT)inname=x;else outname=x;}if(inname.empty()||outname.empty())throw std::runtime_error("one input/output required");for(size_t k=0;k<n;++k){S s;ck(cudaStreamCreate(&s.stream),"stream");for(auto*e:{&s.done,&s.p0,&s.p1,&s.i0,&s.i1,&s.d0,&s.d1})ck(cudaEventCreate(e),"event");s.ctx.reset(eng->createExecutionContext());if(!s.ctx)throw std::runtime_error("context");slots.push_back(std::move(s)); staging.emplace_back();}}
~Impl(){for(auto&s:slots){if(s.stream)cudaStreamSynchronize(s.stream);if(s.in)cudaFree(s.in);if(s.out)cudaFree(s.out); for(auto p: staging[&s-&slots[0]]) cudaFree(p);for(auto e:{s.done,s.p0,s.p1,s.i0,s.i1,s.d0,s.d1})if(e)cudaEventDestroy(e);if(s.stream)cudaStreamDestroy(s.stream);}}
void submit(size_t k,const std::vector<cv::Mat>&im,BatchMetadata m){if(k>=slots.size()||im.empty()||im.size()>4)throw std::invalid_argument("invalid slot/batch");S&s=slots[k];auto d=nvinfer1::Dims4((int)im.size(),3,size.height,size.width);if(!s.ctx->setInputShape(inname.c_str(),d))throw std::invalid_argument("batch outside optimization profile");auto od=s.ctx->getTensorShape(outname.c_str());size_t oe=1;for(int i=0;i<od.nbDims;++i){if(od.d[i]<0)throw std::runtime_error("unresolved output shape");oe*=od.d[i];}size_t ie=im.size()*3ull*size.width*size.height;if(s.inbytes<ie){if(s.in)cudaFree(s.in);ck(cudaMalloc(&s.in,ie*sizeof(float)),"input alloc");s.inbytes=ie;}if(s.outbytes<oe*sizeof(float)){if(s.out)cudaFree(s.out); for(auto p: staging[&s-&slots[0]]) cudaFree(p);ck(cudaMalloc(&s.out,oe*sizeof(float)),"output alloc");s.outbytes=oe*sizeof(float);}s.host.resize(oe);s.meta=std::move(m);for(size_t j=0;j<im.size();++j){if(im[j].empty()||im[j].type()!=CV_8UC3)throw std::invalid_argument("images must be CV_8UC3");cv::Mat r;cv::resize(im[j],r,size);void*d{};ck(cudaMalloc(&d,r.total()*3),"staging alloc");ck(cudaMemcpyAsync(d,r.data,r.total()*3,cudaMemcpyHostToDevice,s.stream),"upload");norm<<<dim3((size.width+15)/16,(size.height+15)/16),dim3(16,16),0,s.stream>>>((unsigned char*)d,(float*)s.in,(int)size.width,(int)size.height,(int)size.width*3,(int)j);ck(cudaGetLastError(),"preprocess");cudaFree(d);}if(!s.ctx->setTensorAddress(inname.c_str(),s.in)||!s.ctx->setTensorAddress(outname.c_str(),s.out))throw std::runtime_error("tensor address");ck(cudaEventRecord(s.p0,s.stream),"p0");if(!s.ctx->enqueueV3(s.stream))throw std::runtime_error("enqueueV3");ck(cudaEventRecord(s.i1,s.stream),"i1");ck(cudaMemcpyAsync(s.host.data(),s.out,s.outbytes,cudaMemcpyDeviceToHost,s.stream),"download");ck(cudaEventRecord(s.done,s.stream),"done");}
bool ready(size_t k)const{return cudaEventQuery(slots[k].done)==cudaSuccess;} GpuBatchResult collect(size_t k){S&s=slots.at(k);ck(cudaEventSynchronize(s.done),"completion");GpuBatchResult r{s.meta,std::move(s.host),{},0,0,0};auto d=s.ctx->getTensorShape(outname.c_str());for(int i=0;i<d.nbDims;++i)r.output_shape.push_back(d.d[i]);r.inference_ms=0;return r;}};
TensorRtBackend::TensorRtBackend(const std::string&e,size_t n,cv::Size z):impl_(std::make_unique<Impl>(e,n,z)){} TensorRtBackend::~TensorRtBackend()=default; void TensorRtBackend::submit(size_t s,const std::vector<cv::Mat>&i,BatchMetadata m){impl_->submit(s,i,std::move(m));} bool TensorRtBackend::ready(size_t s)const{return impl_->ready(s);} GpuBatchResult TensorRtBackend::collect(size_t s){return impl_->collect(s);}
}
